### ISSUE TITLE
Section Purger should implement invalidateEverything and invalidateUrls

### ISSUE THREAD

**Issue by malcolmp** [section/section_purger#12]
Adding these additional purge integrations will allow us to purge individual urls and the entire site cache if necessary.

see https://git.drupalcode.org/project/acquia_purge/blob/8.x-1.x/src/Plugin/Purge/Purger/AcquiaCloudPurger.php

**Comment by AskAlice** [comment]
this has be implemented. See #14 

Depending on when you read this, you may need to wait until the pull request is accepted, or just clone from that branch.
