### ISSUE TITLE
Section purger should process invalidations over a single requests

### ISSUE THREAD

**Issue by malcolmp** [section/section_purger#15]
As currently implemented, the section_purger makes individual HTTP requests for each invalidation. Given the number of tag invalidations that can be involved with common operations such as saving a node, it would be preferable to use a single request.

This is how the acquia_purge module integrates with Acquia's Varnish.
https://git.drupalcode.org/project/acquia_purge/blob/8.x-1.x/src/Plugin/Purge/Purger/AcquiaCloudPurger.php

**Comment by AskAlice** [comment]
Will work on this over this week.

**Comment by AskAlice** [comment]
Closing due to #17

**Comment by AskAlice** [comment]
Release is published @ https://github.com/section/section_purger/releases/tag/v0.2.0
