### ISSUE TITLE
Hash cache tags in headers and use new header name

### ISSUE THREAD

**Issue by malcolmp** [section/section_purger#16]
To avoid issues with the header size in the response the acquia_purge module hashes them. 
https://git.drupalcode.org/project/acquia_purge/blob/8.x-1.x/src/Plugin/Purge/TagsHeader/AcquiaPurgeTagsHeader.php
https://git.drupalcode.org/project/acquia_purge/blob/8.x-1.x/src/Hash.php

The cache tag header should also similarly be updated to Section-Purge-Tags to differentiate it from the base HTTP purger header.

**Comment by AskAlice** [comment]
Makes sense, since varnish would just hash that anyway

**Comment by AskAlice** [comment]
Closing due to #17
