### ISSUE TITLE
Error in sendReq exception handler

### ISSUE THREAD

**Issue by malcolmp** [section/section_purger#19]
This catch block is trying to log the status code but it does not have access to the $response. This causes the below error.

```
Error: Call to a member function getStatusCode() on null in Drupal\section_purger\Plugin\Purge\Purger\SectionPurgerBase->sendReq() (line 114 of /mnt/www/html/asf802dev/docroot/modules/contrib/section_purger/src/Plugin/Purge/Purger/SectionPurgerBase.php).
```

https://github.com/section/section_purger/blob/260ff97b44cd533278d44770b3dd3abd39960229/src/Plugin/Purge/Purger/SectionPurgerBase.php#L114

**Comment by AskAlice** [comment]
closed due to #20
