### ISSUE TITLE
InvalidExpressionException not found

### ISSUE THREAD

**Issue by malcolmp** [section/section_purger#21]
I've encountered a few of these exceptions in the section purger while just navigating through the admin. It appears like there is a missing class reference.

Error: Class 'Drupal\section_purger\Plugin\Purge\Purger\InvalidExpressionException' not found in Drupal\section_purger\Plugin\Purge\Purger\SectionBundledPurger->group() (line 62 of /mnt/www/html/asf802dev/docroot/modules/contrib/section_purger/src/Plugin/Purge/Purger/SectionBundledPurger.php) #0 /mnt/www/html/asf802dev/docroot/modules/contrib/section_purger/src/Plugin/Purge/Purger/SectionBundledPurger.php(79): Drupal\section_purger\Plugin\Purge\Purger\SectionBundledPurger->group(Array)

**Comment by AskAlice** [comment]
#22
