### ISSUE TITLE
SectionBundledPurger group validation fails on parse_url

### ISSUE THREAD

**Issue by malcolmp** [section/section_purger#23]
The section purger is throwing exceptions on some tag invalidations because it is trying to validate them using parse_url despite the fact that they are not urls.

The problematic code is here:
https://github.com/section/section_purger/blob/151760c8f64de84588698fe5616ba4a6fbe8011e/src/Plugin/Purge/Purger/SectionBundledPurger.php#L60

An example we are seeing that fails:
```
URL Invalidation failed with user_reaction:76406
```

**Comment by AskAlice** [comment]
That's frustrating, I'm sorry it looks like that block of code was filled with some placeholder content that was present before I first implemented and tested that function. Seems related to a previous issue similar to this. I looked around and don't see anything else related, though. putting in a PR now

**Comment by AskAlice** [comment]
https://github.com/section/section_purger/releases/tag/v0.2.3
