### ISSUE TITLE
Remaining plugin id updates from #3

### ISSUE THREAD

**Issue by malcolmp** [section/section_purger#7]
This is a follow-up to #3 .

1. The id of the plugin https://github.com/section/section_purger/blob/master/src/Plugin/Purge/Purger/SectionPurger.php needs to be a valid Drupal id such as `section_purger `
2. The ConfigurationCheck also needs an updated id and to reference the `section_purger` plugin instead of the http plugins.

As is the section_purger configuration form isn't being shown as an option in the purge ui.

**Comment by aschreck** [comment]
Thanks Malcolm — when you say that the section_purger configuration form isn't shown as an option in the purge UI, do you mean this form isn't properly showing up for you?

![image](https://user-images.githubusercontent.com/29213917/59384260-07732500-8d1f-11e9-87a3-02ee6609be7a.png)

**Comment by aschreck** [comment]
Nevermind — understand the issue!
